package main;

import common.BaseGUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import typer.tGUI;
import clicker.cGUI;

/**
 * Main class and GUI for RoboClicker
 *
 * @author David
 */
public class StartGUI extends BaseGUI {

    // Program info
    public static final String NAME = "RoboDoer";
    public static final double VERSION = 1.0;

    // Main GUI
    private static StartGUI mainGUI;

    /**
     * Main method entry point
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // Set look and feel
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException e) {
            System.err.print(e.toString());
            System.exit(1);
        }

        // Create GUI
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                // Initialize GUIs
                mainGUI = new StartGUI();

                // Get screen info
                Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
                int SCREEN_W = (int) screen.getWidth();

                // Make adjustments to frame
                mainGUI.setVisible(true);
                mainGUI.setTitle(NAME + " V" + VERSION + " - by David C, 2020");
                int frameXPos = (SCREEN_W / 2) - (mainGUI.getWidth() / 2);
                mainGUI.setLocation(frameXPos, 39);
                mainGUI.setResizable(false);
                mainGUI.setDefaultCloseOperation(EXIT_ON_CLOSE);
            }
        });
    }

    /**
     * Creates GUI
     */
    public StartGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JMenuBar jMenuBar2 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu3 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem2 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem3 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem4 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem6 = new javax.swing.JMenuItem();
        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JLabel title2 = new javax.swing.JLabel();
        javax.swing.JButton clickBut = new javax.swing.JButton();
        javax.swing.JButton typerBut = new javax.swing.JButton();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(820, 579));

        panel.setBackground(new java.awt.Color(255, 182, 81));
        panel.setForeground(new java.awt.Color(255, 255, 255));
        panel.setName("panel"); // NOI18N
        panel.setPreferredSize(new java.awt.Dimension(810, 575));

        title2.setFont(new java.awt.Font("Segoe UI", 3, 64)); // NOI18N
        title2.setForeground(new java.awt.Color(0, 0, 0));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("RoboDoer");
        title2.setName("title"); // NOI18N

        clickBut.setBackground(new java.awt.Color(153, 153, 255));
        clickBut.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        clickBut.setForeground(new java.awt.Color(0, 0, 0));
        clickBut.setText("RoboClicker");
        clickBut.setName("clickerBut"); // NOI18N
        clickBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickButActionPerformed(evt);
            }
        });

        typerBut.setBackground(new java.awt.Color(153, 153, 255));
        typerBut.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        typerBut.setForeground(new java.awt.Color(0, 0, 0));
        typerBut.setText("RoboTyper");
        typerBut.setName("typerBut"); // NOI18N
        typerBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typerButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(clickBut, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(typerBut, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typerBut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clickBut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(null);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Click button
     *
     * @param evt
     */
    private void clickButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickButActionPerformed

        // Hide start menu
        mainGUI.setVisible(false);

        // Open clicker GUI
        cGUI.start();
    }//GEN-LAST:event_clickButActionPerformed

    private void typerButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typerButActionPerformed

        // Hide start menu
        mainGUI.setVisible(false);

        // Open typer GUI
        tGUI.start();
    }//GEN-LAST:event_typerButActionPerformed

    /**
     * The action attached to the Start Clicking button
     *
     * @param evt
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
